version: "3.4"
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "1111:1111"
    links:
      - "mariadb:localhost"
    depends_on:
      - mariadb

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.db